package _draft.test;

import cn.hutool.core.lang.Assert;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.client.CookieStore;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.BasicCookieStore;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.impl.cookie.BasicClientCookie;
import org.springframework.util.FileCopyUtils;

import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.charset.Charset;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static _utils.http.HttpUtil.HTTP_STATUS_OK;

/**
 *
 * Copyright https://wtfu.site Inc. All Rights Reserved.
 * 
 * @date 2022/8/30
 *                          @since  1.0
 *                          @author 12302
 * 
 */
public class TongRenTang {

    public static void main(String[] args) {


        /**
         * # Netscape HTTP Cookie File
         * # http://curl.haxx.se/rfc/cookie_spec.html
         * # This file was generated by EditThisCookie
         * zhongduan.tongrentang.com	FALSE	/	FALSE	1664420937	BMAP_SECKEY	cNbu9x-gLuw7SJKKV0L4cJKouvquBh7kDpTzWtThslNTB9cGEmmsYCucn0m_PL9ozWc1ebK1nVgGs8kYgb8SMuga6W5_HMUDqP9WObkubGB6nV6bHYHI12BtxNuh7ND3EfeKJ6nKmBiGXYJ7pw-nfL9p9GOZMsp-J3PLx6Z9BjYxhg9QgwtMSupO71YgndVQ
         * zhongduan.tongrentang.com	FALSE	/	FALSE	1661915336	LAT	39.91092455
         * zhongduan.tongrentang.com	FALSE	/	FALSE	1661915336	LNG	116.4133837
         * zhongduan.tongrentang.com	FALSE	/	FALSE	0	PHPSESSID	k423f68oeqgfeq347koodgpf97
         * zhongduan.tongrentang.com	FALSE	/	FALSE	1664420937	SECKEY_ABVK	Q93uxRFBnxtajs2S2dBfLcgVUGApYVehBNvnpO8L840%3D
         */

        CookieStore cookieStore = new BasicCookieStore();
        //添加cookie
        //放入cookiestore
        cookieStore.addCookie(new BasicClientCookie("BMAP_SECKEY", "cNbu9x-gLuw7SJKKV0L4cJKouvquBh7kDpTzWtThslNTB9cGEmmsYCucn0m_PL9ozWc1ebK1nVgGs8kYgb8SMuga6W5_HMUDqP9WObkubGB6nV6bHYHI12BtxNuh7ND3EfeKJ6nKmBiGXYJ7pw-nfL9p9GOZMsp-J3PLx6Z9BjYxhg9QgwtMSupO71YgndVQ"));
        cookieStore.addCookie(new BasicClientCookie("PHPSESSID","k423f68oeqgfeq347koodgpf97"));
        cookieStore.addCookie(new BasicClientCookie("SECKEY_ABVK","Q93uxRFBnxtajs2S2dBfLcgVUGApYVehBNvnpO8L840%3D"));


        HttpClient httpClient = HttpClients.custom()
                //.setDefaultCookieStore(cookieStore)//设置Cookie
                .build();

        String[] citys = new String[]{
                "东城区","西城区","朝阳区","丰台区","石景山区",
                "海淀区","门头沟区","房山区","通州区","顺义区",
                "昌平区","大兴区","怀柔区","平谷区","密云区",
                "延庆区"
        };

        JSONArray array = new JSONArray();

        for (int i = 0; i < citys.length; i++) {
            array.add(getKindOfCity(httpClient,citys[i]));
        }

        System.out.println(array);
    }

    public static String decodeUnicode(String str) {
        Charset set = Charset.forName("UTF-16");
        Pattern p = Pattern.compile("\\\\u([0-9a-fA-F]{4})");
        Matcher m = p.matcher(str);
        int start = 0;
        int start2 = 0;
        StringBuffer sb = new StringBuffer();
        while (m.find(start)) {
            start2 = m.start();
            if (start2 > start) {
                String seg = str.substring(start, start2);
                sb.append(seg);
            }
            String code = m.group(1);
            int i = Integer.valueOf(code, 16);
            byte[] bb = new byte[4];
            bb[0] = (byte) ((i >> 8) & 0xFF);
            bb[1] = (byte) (i & 0xFF);
            ByteBuffer b = ByteBuffer.wrap(bb);
            sb.append(String.valueOf(set.decode(b)).trim());
            start = m.end();
        }
        start2 = str.length();
        if (start2 > start) {
            String seg = str.substring(start, start2);
            sb.append(seg);
        }
        return sb.toString();
    }


    public static JSONObject getKindOfCity(HttpClient httpClient,String cityName){
        Assert.notEmpty(cityName);
        String url = "https://zhongduan.tongrentang.com/wx/index/index?city_id=%E5%8C%97%E4%BA%AC%E5%B8%82&area=" + cityName;
        HttpGet httpRequest = new HttpGet(url);

        InputStream inputStream = null;
        HttpResponse httpResponse;
        try {
            httpResponse = httpClient.execute(httpRequest);
            if (httpResponse.getStatusLine().getStatusCode() == HTTP_STATUS_OK) {
                HttpEntity httpEntity = httpResponse.getEntity();
                inputStream = httpEntity.getContent();

                String rst = new String(FileCopyUtils.copyToByteArray(inputStream), "UTF-8");
                rst = decodeUnicode(rst);
                System.out.println(rst);
                JSONObject jsonObject = JSON.parseObject(rst);
                jsonObject.put("city",cityName);
                return jsonObject;
            }else{
                throw new RuntimeException("哈哈");
            }
        } catch (Exception e) {e.printStackTrace(); return null;}
    }

}
